### ISSUE TITLE
v1.1.0 breaks if no options passed

### ISSUE THREAD

**Issue by allthepies** [rrainn/aws-mockify#1]
I had to change
const ddb = new MockAWS.DynamoDB();

to 

const ddb = new MockAWS.DynamoDB(undefined, {});

otherwise I got a "cannot access options of undefined" error.  Perhaps the options param needs a default empty object set ?

**Comment by fishcharlie** [comment]
@allthepies **So** sorry about this. v1.1.1 has been released which should fix this.

**Comment by allthepies** [comment]
Thanks!
